### ISSUE TITLE
Highlight top 3 bin (based on max counts) from histogram

### ISSUE THREAD

**Issue by gponce-ars** [yutannihilation/gghighlight#106]
Is there a way to highlight the top 3 bins (top N) based on max counts in the geom_histogram using gghighlight?

Something like this, where bars are highlighted and labeled with the bin-middle value?

![image](https://user-images.githubusercontent.com/20215136/55207373-0fe3a700-5197-11e9-9215-9ac317e857a0.png)

**Comment by yutannihilation** [comment]
No, gghighlight cannot use calculated values by ggplot2. To do this, you have to bin and count by yourself and use `geom_col()` instead of `geom_histogram()`.

By the way, you can do this with plain ggplot2.

``` r
library(ggplot2)

ggplot(diamonds, aes(carat)) +
  geom_histogram(aes(fill = stat(count) > 10000)) +
  scale_fill_manual(values = c(`TRUE` = "magenta4", `FALSE` = alpha("grey", 0.7)))
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
```

![](https://i.imgur.com/ViD7sc0.png)

<sup>Created on 2019-03-29 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by gponce-ars** [comment]
Got it. Thanks!
