### ISSUE TITLE
greyout intervals on lines

### ISSUE THREAD

**Issue by uasolo** [yutannihilation/gghighlight#201]
curve <- tibble(x = seq(0, 1, by = 0.01), y = rnorm(101))

ggplot(curve) +
  aes(x, y) +
  geom_line() +
  gghighlight(x < 0.1 | x > 0.3)

the black curve is not interrupted in the interval 0.1 < x < 0.3 , it shows connected. 
This is clearly not the intended result. I would like to know if this is anything that can be fixed, changed, is it a bug or not. Thank you!

**Comment by uasolo** [comment]
https://forum.posit.co/t/highlight-lines-in-ggplot/135165/2 
for the same problem

**Comment by yutannihilation** [comment]
This is the intended result, unfortunately. gghighlight assumes it's either the whole series is highlighted or not. There could be alternative implementation that supports this, but I didn't choose it due to a design decision. Sorry for inconvenience!

You can do this without gghighlight, by the way. Hope this helps.

``` r
library(ggplot2)
library(tibble)

curve <- tibble(x = seq(0, 1, by = 0.01), y = rnorm(101))

ggplot(curve, aes(x, y, colour = ifelse(x < 0.1 | x > 0.3, 1, NA))) +
  geom_line()
```

![](https://i.imgur.com/X0SRoTG.png)

<sup>Created on 2024-07-24 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by uasolo** [comment]
Thank you, that was helpful !
