### ISSUE TITLE
highlight based on shape, not just color

### ISSUE THREAD

**Issue by AbeHandler** [yutannihilation/gghighlight#69]
This is a great package! I want to make figures that are also readable for people who are color blind. Is it possible to add support for highlighting based on shape, in addition to highlighting based on color? 

```
e.g. 
ggplot(d, aes(x, y, colour = type)) +
  geom_point(size = 10) +
  gghighlight(type == "b", shape="square")
```

**Comment by yutannihilation** [comment]
Since #62 is not closed, this is basically possible. But, I found different shapes won't hide unhighlighted points completely. For example:

``` r
library(gghighlight)
#> Loading required package: ggplot2

set.seed(2)
d <- data.frame(x = runif(20), y = runif(20), type = sample(c("a", "b", "c"), 20, replace = TRUE))

ggplot(d, aes(x, y, colour = type, shape = type)) +
  geom_point(size = 10) +
  gghighlight(type != "b", unhighlighted_params = list(shape = 19))
#> Warning: You set use_group_by = TRUE, but grouped calculation failed.
#> Falling back to ungrouped filter operation...
#> label_key: type
#> Warning: Ignoring unknown aesthetics: shape
```

![](https://i.imgur.com/SFqoMmz.png)

<sup>Created on 2018-12-28 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

gghighlight might choose not to draw these underlying points, but, on the other hand, it's useful to keep them when facetting. Both have their pros and cons, and it's a design choice; I choose to focus on `fill` and `colour`, so let me close this issue as "won't fix."

``` r
library(gghighlight)
#> Loading required package: ggplot2

set.seed(2)
d <- data.frame(x = runif(20), y = runif(20), type = sample(c("a", "b", "c"), 20, replace = TRUE))

ggplot(d, aes(x, y, colour = type, shape = type)) +
  geom_point(size = 10) +
  gghighlight(x > 0.5, use_group_by = FALSE) +
  facet_wrap(vars(type))
#> label_key: type
#> Warning: Ignoring unknown aesthetics: shape
```

![](https://i.imgur.com/OkUBVHx.png)

<sup>Created on 2018-12-28 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
