### ISSUE TITLE
Specifying 'x' argument for targeted geom layer.

### ISSUE THREAD

**Issue by mrworthington** [yutannihilation/gghighlight#81]
Hi! 

First, **thanks for the package**! This is an incredibly smart tool. My issue is related to the 'sf' package support. Given that I often use supplemental layers to create my publication-ready maps, I was wondering if there's a way to specify the target layer for which I wanting `gghighlight` to utilize, given that plotting multiple `geom_sf` layers seems to confuse gghighlight because it doesn't know what to inherit for it's filter. 

The error I get when mapping out code similar to the example below is: 

`Error in ggplot_add.gg_highlighter(object, p, objectname) : 
  there is no layer to highlight!`

Do you have a suggestion on how to resolve this? I've tried a number of different things (including putting `nc` directly in the `ggplot()` call with it's aesthetic mappings, but gghighlight seems to keep getting confused about what to inherit.

```
gg_map <- nc %>%
  ggplot() +
  gghighlight(grepl("^[A-C]", NAME)) +
  geom_sf(data=coast, fill = "aliceblue", color = "aliceblue", alpha = 0.6) + # Supplemental Layer 1
  geom_sf(data=us_states, fill = "white", color = "gray62", alpha = 0.7) + # Supplemental Layer 2
  geom_sf(data=nc, aes(fill = AREA), alpha = 0.8) + # Target Layer for gghighlight
  ggtitle("Polygons whose names start with A-C are highlighted!")

gg_map
```

**Comment by yutannihilation** [comment]
Thanks for reporting. This seems a complicated issue, but I feel this is a gghighlight's bug.

Is this similar to what you want to draw? (Note that this might not reproducible on your environment since I'm using the dev version of ggplot2) I don't know where that `coast` come from...

``` r
library(ggplot2)
library(gghighlight)
library(sf)
#> Linking to GEOS 3.6.1, GDAL 2.2.3, PROJ 4.9.3

data(tornados, package = "GISTools")

nc <- st_read(system.file("shape/nc.shp", package = "sf"), quiet = TRUE)
us_states <- st_as_sf(us_states)
#> Loading required package: sp

ggplot(nc, aes(fill = AREA)) +
  geom_sf(data=us_states, fill = "white", color = "gray62", alpha = 0.7) + # Supplemental Layer 2
  geom_sf(data=nc, alpha = 0.8) + # Target Layer for gghighlight
  gghighlight(grepl("^[A-C]", NAME), n = 1) +
  ggtitle("Polygons whose names start with A-C are highlighted!")
```

![](https://i.imgur.com/mH2aIe4.png)

<sup>Created on 2019-01-04 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

First of all, unlike usual layers of ggplot2, `gghighlight()` modifies the plot immediately, not at the time of rendering the plot. This requires the plot to contain the layer to highlight *at the time of adding `gghighlight()`.* So, the following fails because the layer is added after `gghighlight()`.

``` r
ggplot(mtcars, aes(wt, mpg)) +
  gghighlight() +
  geom_point(cyl > 6)
```

This succeeds on the other hand:

``` r
ggplot(mtcars, aes(wt, mpg)) +
  geom_point() +
  gghighlight(cyl > 6)
```

`gghighlight()` also assumes the predicate is can be used for every layer, so this fails because `annotate()`'s data doesn't contain `cyl` column:

``` r
ggplot(mtcars, aes(wt, mpg)) +
  annotate("text", x = 2, y = 20, label = "foo") +
  geom_point() +
  gghighlight(cyl > 6)
```

In this case, you can use `n` to limit how many layers above to highlight (but, this is not effective for all cases)

``` r
ggplot(mtcars, aes(wt, mpg)) +
  annotate("text", x = 2, y = 20, label = "foo") +
  geom_point() +
  gghighlight(cyl > 6, n = 1)
```

Besides, this issue is also related to `geom_sf()`'s specialness about `geometry` aesthetic, but I'm yet to figure out the supposed behaviour.
